# Generated by Django 5.1.6 on 2025-04-22 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0004_workflowexecution_execution_context_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodeconnection",
            name="source_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outputs",
                to="workflows.node",
            ),
        ),
        migrations.AlterField(
            model_name="nodeconnection",
            name="target_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inputs",
                to="workflows.node",
            ),
        ),
    ]
