# Generated by Django 5.1.6 on 2025-04-18 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0001_initial'),
        ('workflows', '0004_workflowexecution_execution_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('port_type', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], max_length=10)),
                ('data_type', models.CharField(default='any', max_length=50)),
                ('optional', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='workflows.node')),
            ],
            options={
                'unique_together': {('node', 'name', 'port_type')},
            },
        ),
    ]
