# Generated by Django 5.1.6 on 2025-06-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_integration", "0002_nodeport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelconfig",
            name="provider",
            field=models.CharField(
                choices=[
                    ("OPENAI", "OpenAI"),
                    ("ANTHROPIC", "Anthropic (Claude)"),
                    ("DEEPSEEK", "DeepSeek"),
                    ("OLLAMA", "Ollama"),
                    ("HUGGINGFACE", "Hugging Face"),
                    ("GEMINI", "Gemini"),
                ],
                max_length=20,
            ),
        ),
    ]
