import time
import random
from ..ai_providers import AIProvider

class MockProvider(AIProvider):
    """
    Mock AI provider for demos and testing.
    Returns realistic-looking responses based on prompt patterns.
    """
    
    def __init__(self, api_key: str = "mock-key", model_name: str = "mock-model"):
        self.api_key = api_key
        self.model_name = model_name
        
        # Demo response templates
        self.responses = {
            'greeting': [
                "Hello! I'm a mock AI assistant ready to help with your demo. What would you like to explore today?",
                "Hi there! I'm simulating an AI response for your demonstration. How can I assist you?",
                "Greetings! This is a mock response to showcase the InnoFlow platform capabilities."
            ],
            'code': [
                """Here's a Python function that solves your request:

```python
def demo_function(input_data):
    \"\"\"
    This is a mock code generation example
    for your InnoFlow demonstration.
    \"\"\"
    result = process_data(input_data)
    return f"Processed: {result}"

# Example usage:
output = demo_function("demo input")
print(output)
```

This code demonstrates how AI can generate functional programming solutions through InnoFlow's workflow system.""",
                
                """Here's a JavaScript solution for your demo:

```javascript
async function handleDemo(userInput) {
    // Mock AI-generated code for demonstration
    const processedData = await processInput(userInput);
    
    return {
        success: true,
        result: processedData,
        message: "Generated by InnoFlow AI Integration"
    };
}

// This showcases InnoFlow's ability to integrate AI code generation
const result = await handleDemo("your demo input");
console.log(result);
```"""
            ],
            'analysis': [
                """Based on your input, here's my analysis:

**Key Insights:**
• The data shows strong potential for automation
• InnoFlow's workflow system can handle this efficiently  
• Integration with AI providers offers significant value

**Recommendations:**
1. Implement the proposed workflow structure
2. Use multiple AI providers for redundancy
3. Monitor performance through analytics dashboard

**Expected Outcomes:**
- 40% reduction in processing time
- Improved accuracy through AI validation
- Scalable solution for future requirements

This analysis demonstrates InnoFlow's AI-powered decision support capabilities.""",

                """## Comprehensive Analysis Results

**Performance Metrics:**
- Processing Speed: 95% improvement
- Accuracy Rate: 98.5% 
- User Satisfaction: Excellent

**Technical Assessment:**
The current implementation shows strong architecture with room for optimization. The AI integration layer provides robust functionality while maintaining flexibility for future enhancements.

**Business Impact:**
This solution can significantly improve operational efficiency and provide measurable ROI through automated workflows and intelligent decision-making capabilities.

*Generated by InnoFlow AI Analytics Engine*"""
            ],
            'creative': [
                """🎨 **Creative AI Response for Your Demo**

Imagine a world where workflows flow like rivers,
Each node a stepping stone across the stream,
Where AI providers work as skilled deliverers,
Bringing intelligence to every team's dream.

InnoFlow bridges the gap between human creativity and artificial intelligence, creating a symphony of automated processes that adapt, learn, and evolve with your business needs.

**Key Features Highlighted:**
✨ Seamless AI integration
🔄 Dynamic workflow orchestration  
📊 Real-time analytics and monitoring
🛠️ Drag-and-drop interface design

*This creative response showcases InnoFlow's ability to handle diverse content types and creative AI applications.*""",

                """🚀 **Innovation Spotlight: AI-Powered Creativity**

**Your Demo Concept: "The Future of Work"**

In this vision, teams collaborate with AI partners through InnoFlow's intuitive platform:

• **Content Creation**: AI generates first drafts, humans refine and perfect
• **Process Optimization**: Machine learning identifies improvement opportunities  
• **Decision Support**: Data-driven insights guide strategic choices
• **Automation**: Routine tasks handled seamlessly by intelligent workflows

**Demo Highlight**: Watch as a simple prompt transforms into comprehensive solutions through our multi-provider AI ecosystem, showcasing the power of human-AI collaboration.

*Powered by InnoFlow's Advanced AI Integration Platform*"""
            ],
            'business': [
                """📈 **Business Intelligence Demo Report**

**Executive Summary:**
InnoFlow's AI integration platform delivers measurable business value through intelligent automation and workflow optimization.

**Key Performance Indicators:**
- ROI: 340% within first year
- Efficiency Gains: 65% reduction in manual tasks
- Error Reduction: 89% improvement in accuracy
- Time to Market: 45% faster delivery cycles

**Strategic Advantages:**
✅ Multi-provider AI integration reduces vendor lock-in
✅ Visual workflow design accelerates development
✅ Real-time monitoring ensures optimal performance
✅ Scalable architecture supports business growth

**Implementation Roadmap:**
1. **Phase 1**: Core AI provider integration (2 weeks)
2. **Phase 2**: Workflow automation deployment (4 weeks)  
3. **Phase 3**: Advanced analytics and optimization (6 weeks)

*This report demonstrates InnoFlow's business value proposition and implementation strategy.*""",

                """💼 **Strategic AI Implementation Analysis**

**Market Opportunity Assessment:**
The AI automation market is projected to reach $35.8B by 2025, with workflow automation representing the fastest-growing segment.

**Competitive Advantages:**
- **Unified Platform**: Single interface for multiple AI providers
- **Visual Design**: No-code workflow creation
- **Enterprise Security**: SOC2 compliant architecture
- **Flexible Integration**: API-first design philosophy

**Risk Mitigation:**
• Provider redundancy prevents service disruptions
• Comprehensive monitoring ensures performance visibility
• Gradual rollout minimizes implementation risks
• Built-in fallback mechanisms maintain service continuity

**Expected Business Outcomes:**
- Operational cost reduction: 30-50%
- Developer productivity increase: 200%+
- Customer satisfaction improvement: 85%+

*Generated by InnoFlow Business Intelligence Module*"""
            ]
        }
    
    def generate_completion(self, prompt: str, **kwargs) -> str:
        """
        Generate a mock response based on prompt content
        """
        # Simulate realistic AI response time
        time.sleep(random.uniform(0.5, 2.0))
        
        prompt_lower = prompt.lower()
        
        # Detect prompt type and return appropriate response
        if any(word in prompt_lower for word in ['hello', 'hi', 'hey', 'greetings']):
            response_type = 'greeting'
        elif any(word in prompt_lower for word in ['code', 'function', 'program', 'script', 'python', 'javascript']):
            response_type = 'code'
        elif any(word in prompt_lower for word in ['analyze', 'analysis', 'insights', 'data', 'metrics']):
            response_type = 'analysis'
        elif any(word in prompt_lower for word in ['creative', 'story', 'poem', 'imagine', 'design']):
            response_type = 'creative'
        elif any(word in prompt_lower for word in ['business', 'revenue', 'profit', 'strategy', 'market']):
            response_type = 'business'
        else:
            # Default comprehensive response
            return f"""✨ **InnoFlow AI Demo Response**

**Your Input:** "{prompt[:100]}{'...' if len(prompt) > 100 else ''}"

**AI Analysis:** I've processed your request using InnoFlow's advanced AI integration system. Here's a comprehensive response:

**Generated Solution:**
Based on your prompt, I recommend implementing a workflow that combines multiple AI providers for optimal results. This approach ensures reliability, performance, and flexibility.

**Key Benefits:**
• Multi-provider redundancy for 99.9% uptime
• Real-time performance monitoring and optimization
• Seamless integration with existing business processes
• Scalable architecture supporting future growth

**Implementation Steps:**
1. Configure AI provider credentials and models
2. Design workflow using visual drag-and-drop interface
3. Test and validate using built-in playground
4. Deploy with comprehensive monitoring and analytics

**Expected Results:**
- Response Time: <2 seconds average
- Accuracy Rate: 95%+ for domain-specific tasks
- Cost Optimization: 40% reduction vs individual providers
- Developer Productivity: 3x improvement

*This demonstrates InnoFlow's ability to handle diverse AI workloads with enterprise-grade reliability and performance.*

🚀 **Ready for Production Deployment!**"""
        
        # Return random response from the detected category
        responses = self.responses.get(response_type, self.responses['greeting'])
        return random.choice(responses) 