# Generated by Django 5.1.6 on 2025-06-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
